name: Prepare mdi update

on: push

# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # - run: yarn install
      # - run: node scripts/prepare-mdi-update.js
      - run: git --version
      - run: jq --version
  # publish-npm:
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #         registry-url: https://registry.npmjs.org/
  #     - uses: Borales/actions-yarn@1.1.0
  #     - run: yarn publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}
