name: Publish mdi update

on:
  push:
    branches:
      - master

jobs:
  create-release-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: ./scripts/create-mdi-release.sh --with-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-publish:
    runs-on: ubuntu-latest
    needs: [create-release-commit]
    strategy:
      matrix:
        package: [react, preact]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: ./scripts/create-mdi-release.sh --with-build-and-publish ${{ matrix.package }}
